// Origami image metadata — fill in model and designer for each image.
const origamiData = {
  "IMG_3138.webp":  { model: "Mask (I forget the exact name)", designer: "Joel Cooper" },
  "IMG_3324.webp":  { model: "Phoenix", designer: "Satoshi Kamiya" },
  "IMG_3912.webp":  { model: "Eagle", designer: "Hoang Trung Thanh" },
  "IMG_3924.webp":  { model: "Hippo", designer: "Birb" },
  "IMG_3925.webp":  { model: "Hippo", designer: "Birb" },
  "IMG_4069.webp":  { model: "Parasaurolophus", designer: "Shuki Kato" },
  "IMG_4251.webp":  { model: "Giganotosaurus", designer: "Shuki Kato" },
  "IMG_4259.webp":  { model: "Giganotosaurus", designer: "Shuki Kato" },
  "IMG_4435.webp":  { model: "Loggerhead Sea Turtle", designer: "Satoshi Kamiya" },
  "IMG_4437.webp":  { model: "Loggerhead Sea Turtle", designer: "Satoshi Kamiya" },
  "IMG_4456.webp":  { model: "Shiba Inu", designer: "Shun Kato" },
  "IMG_4523.webp":  { model: "Bactrian Camel", designer: "Shuki Kato" },
  "IMG_4681.webp":  { model: "Grim Reaper", designer: "Miyamoto Chuya" },
  "IMG_4683.webp":  { model: "Grim Reaper", designer: "Miyamoto Chuya" },
  "IMG_4769.webp":  { model: "Walking in Rain", designer: "Chen Xiao (Obelisk)" },
  "IMG_5032.webp":  { model: "Lich King", designer: "Nguyen Tuan Anh" },
  "IMG_5146.webp":  { model: "Tiger", designer: "Satoshi Kamiya" },
  "IMG_5158.webp":  { model: "Great White Shark", designer: "Nguyen Hung Cuong" },
  "IMG_5333.webp":  { model: "Zero Fighter", designer: "Satoshi Kamiya" },
  "IMG_6015.webp":  { model: "Bison", designer: "Shuki Kato" },
  "IMG_6016.webp":  { model: "Bison", designer: "Shuki Kato" },
  "IMG_7992.webp":  { model: "Black Forest Cuckoo Clock", designer: "Robert Lang" },
  "IMG_8126.webp":  { model: "Fugu", designer: "Sipho Mabona" },
  "IMG_8129.webp":  { model: "Fugu", designer: "Sipho Mabona" },
  "IMG_8136.webp":  { model: "Fugu", designer: "Sipho Mabona" },
  "IMG_8214.webp":  { model: "Caiman", designer: "Jeong Jae II" },
  "IMG_8216.webp":  { model: "Caiman", designer: "Jeong Jae II" },
  "IMG_8219.webp":  { model: "Caiman", designer: "Jeong Jae II" },
  "IMG_8245.webp":  { model: "Invention of the Crane", designer: "Origami by Boice" },
  "IMG_8459.webp":  { model: "Eagle", designer: "Ikuno Riku" },
  "IMG_8460.webp":  { model: "Eagle", designer: "Ikuno Riku" },
};
