// Origami image metadata — fill in model and designer for each image.
const origamiData = {
  "IMG_3138.webp":  { model: "Mask (I forget the exact name)", designer: "Joel Cooper" },
  "IMG_3324.webp":  { model: "", designer: "" },
  "IMG_3912.webp":  { model: "", designer: "" },
  "IMG_3924.webp":  { model: "", designer: "" },
  "IMG_3925.webp":  { model: "", designer: "" },
  "IMG_4069.webp":  { model: "", designer: "" },
  "IMG_4251.webp":  { model: "", designer: "" },
  "IMG_4259.webp":  { model: "", designer: "" },
  "IMG_4435.webp":  { model: "", designer: "" },
  "IMG_4437.webp":  { model: "", designer: "" },
  "IMG_4456.webp":  { model: "", designer: "" },
  "IMG_4523.webp":  { model: "", designer: "" },
  "IMG_4681.webp":  { model: "", designer: "" },
  "IMG_4683.webp":  { model: "", designer: "" },
  "IMG_4769.webp":  { model: "", designer: "" },
  "IMG_5032.webp":  { model: "", designer: "" },
  "IMG_5146.webp":  { model: "", designer: "" },
  "IMG_5158.webp":  { model: "", designer: "" },
  "IMG_5333.webp":  { model: "", designer: "" },
  "IMG_6015.webp":  { model: "", designer: "" },
  "IMG_6016.webp":  { model: "", designer: "" },
  "IMG_7992.webp":  { model: "", designer: "" },
  "IMG_8126.webp":  { model: "", designer: "" },
  "IMG_8129.webp":  { model: "", designer: "" },
  "IMG_8136.webp":  { model: "", designer: "" },
  "IMG_8214.webp":  { model: "", designer: "" },
  "IMG_8216.webp":  { model: "", designer: "" },
  "IMG_8219.webp":  { model: "", designer: "" },
  "IMG_8245.webp":  { model: "", designer: "" },
  "IMG_8304.webp":  { model: "", designer: "" },
  "IMG_8305.webp":  { model: "", designer: "" },
  "IMG_8459.webp":  { model: "", designer: "" },
  "IMG_8460.webp":  { model: "", designer: "" },
};
